FROM openjdk:21-slim

#ARG PROFILE
#ARG SENTRY_DSN_ARG
#ARG SENTRY_ENVIRONMENT_ARG

#ENV PROFILE_ENV=$PROFILE
#ENV SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT_ARG
#ENV SENTRY_DSN=$SENTRY_DSN_ARG

COPY ./target/my-app-de-john-0.0.1-SNAPSHOT.jar /usr/src/app/
WORKDIR /usr/src/app

CMD ["java", "-jar", "my-app-de-john-0.0.1-SNAPSHOT.jar"]
